### PR TITLE
GitHubRepositories: Remove `has_wiki` Check from Private Repositories Unit Tests

### LINKED ISSUE #403: GitHubRepositories: Unit Tests are Failing when Checking for `has_wiki` on Private Repositories
#### Issue Details

The `Tests/GithubRepositories.test.ps1` `New-GitHubRepository` unit tests are failing when creating private repositories and checking that the `has_wiki` property is `true`.

This is due to support for Wikis being removed from private repos in the GitHub free tier.

image

#### Steps to reproduce the issue
```powershell
invoke-pester Tests\GitHubRepositories.tests.ps1
```

#### Verbose logs showing the problem

```
[-] GitHubRepositories\New-GitHubRepository.When creating a repository for the authenticated user.When creating a private repository with default settings.Should return the correct properties 34ms (33ms|1ms)
 Expected $true, but got $false.
 at $repo.has_Wiki | Should -BeTrue, Tests\GitHubRepositories.tests.ps1:91
 at <ScriptBlock>, Tests\GitHubRepositories.tests.ps1:91
[-] GitHubRepositories\New-GitHubRepository.When creating an organization repository.When creating a private repository with default settings.Should return the correct properties 19ms (18ms|1ms)
 Expected $true, but got $false.
 at $repo.has_Wiki | Should -BeTrue, Tests\GitHubRepositories.tests.ps1:286
 at <ScriptBlock>, Tests\GitHubRepositories.tests.ps1:286
```

#### Suggested solution to the issue

Remove the `has_wiki` check from the `New-GitHubRepository` unit tests.

#### Requested Assignment

- If possible, I would like to fix this.

#### Operating System

```
OSVersion                      Microsoft Windows NT 10.0.19045.0
Is 64-bit                      True
Current culture                en-GB
Current UI culture             en-GB
```

#### PowerShell Version

```
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

#### Module Version

```
Running: 0.16.1 0.16.1
Installed: 0.16.1
```

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Description

Remove the `has_wiki` property check from the private repositories unit tests as Wikis are no longer supported on the GitHub free tier.

#### Issues Fixed

- Fixes #403

#### References

N/A

#### Checklist

- [ ] You actually ran the code that you just wrote, especially if you did just "one last quick change".
- [ ] Comment-based help added/updated, including examples.
- [ ] [Static analysis](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#static-analysis) is reporting back clean.
- [ ] New/changed code adheres to our [coding guidelines](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#coding-guidelines).
- [ ] [Formatters were created](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#formatters) for any new types being added.
- [ ] New/changed code continues to [support the pipeline](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#pipeline-support).
- [ ] Changes to the manifest file follow the [manifest guidance](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#module-manifest).
- [x] Unit tests were added/updated and are all passing. See [testing guidelines](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#testing).  This includes making sure that all pipeline input variations have been covered.
- [ ] Relevant usage examples have been added/updated in [USAGE.md](https://github.com/microsoft/PowerShellForGitHub/blob/master/USAGE.md).
- [ ] If desired, ensure your name is added to our [Contributors list](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#contributors)

### CODE REVIEW

**Comment by X-Guardian** [comment]
@HowardWolosky, please can you trigger the CI checks on this PR.

**Review by HowardWolosky — COMMENTED** [review]
Thanks for catching and fixing this.  It looks like there are actually 6 UT's that reference `has_Wiki`.  I would have expected that all 6 would need to be removed.  Will Approve the change if the CI run comes back clean.

**Comment by X-Guardian** [comment]
The other unit tests are for public repos which still allow Wikis on the free tier, so that is why they are not broken.

**Review by HowardWolosky — APPROVED** [review]
Thanks for the catch and fix!

**Pull request merged**
