### PR TITLE
Fix Set-GitHubContent Encode Issues

### PR DESCRIPTION
**Pull request by jing8956**
#### Description
The UTF-16 LE encode let my text content many "�“
Is not github view a text file default encoding。

#### Checklist

- [ ] You actually ran the code that you just wrote, especially if you did just "one last quick change".
- [ ] Comment-based help added/updated, including examples.
- [ ] [Static analysis](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#static-analysis) is reporting back clean.
- [ ] New/changed code adheres to our [coding guidelines](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#coding-guidelines).
- [ ] [Formatters were created](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#formatters) for any new types being added.
- [ ] New/changed code continues to [support the pipeline](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#pipeline-support).
- [ ] Changes to the manifest file follow the [manifest guidance](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#module-manifest).
- [ ] Unit tests were added/updated and are all passing. See [testing guidelines](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#testing).  This includes making sure that all pipeline input variations have been covered.
- [ ] Relevant usage examples have been added/updated in [USAGE.md](https://github.com/microsoft/PowerShellForGitHub/blob/master/USAGE.md).
- [ ] If desired, ensure your name is added to our [Contributors list](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#contributors)

### CODE REVIEW

**Review by HowardWolosky — APPROVED** [review]
Good catch!  `Get-GitHubContent` already uses `[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String())` when retrieving the content.  Not sure why we weren't using `UTF8` when setting it.

Thanks for the fix!

**Comment by jorioux** [comment]
When are you planning to release a new version of the module with this fix?

**Comment by jorioux** [comment]
Still not released in the PSGallery, do you have an ETA?

**Comment by HowardWolosky** [comment]
> Still not released in the PSGallery, do you have an ETA?

Not a good one at the moment.  The work on the repo side was done this morning for rev'ing the module, however the module also needs to be signed before it can be published to PSGallery.  Unfortunately, the necessary steps for getting the module _signed_ have changed within Microsoft since the last time a module update was published, and the new process has gotten quite a bit more complicated.  Current (optimistic) ETA at this point to get this project transitioned to the new signing process is likely 2-3 weeks.

**Comment by jorioux** [comment]
@HowardWolosky with all due respect, it's been more than a month now, what is going on? Not having 0.16.1 in the PSGallery is a blocker for my team at "Intact Financial Corporation", we are planning on using this module extensively.

**Comment by HowardWolosky** [comment]
Hi @jorioux,

I'm excited to hear that your company is planning on using this module extensively, and I do apologize that you've been waiting so long for `0.16.1` to be published to PSGallery.

As I [mentioned previously](https://github.com/microsoft/PowerShellForGitHub/pull/328#issuecomment-848885138), the process used internally to get code/files signed with a Microsoft certificate that we ship externally to customers changed in April, and I've been working towards getting this project migrated to that new process.  This is the first time that the process has changed in many, many years.  Without going into unnecessary internal details, I was overly optimistic in that estimate as I've encountered some issues that I continue to work on within the company.   I'm continuing to work through the process internally and when there is a new estimate that I can provide, I will respond here with it.

Is there a specific company policy preventing you from using the code as-is within the repo as opposed to the published module as a workaround for the interim?

**Comment by HowardWolosky** [comment]
Just as a general update here, I continue to be blocked internally by the necessary procedures to be able to get the module signed and updated to PowerShellGallery.  I _am_ working with the necessary parties to get things unblocked, but it's continuing to take much more time than anyone had originally anticipated due to the new process that was created.

**Comment by samsmithnz** [comment]
@HowardWolosky Any updates on a 0.16.1 release? This is affecting a big customer of mine/ours.

**Comment by HowardWolosky** [comment]
> @HowardWolosky Any updates on a 0.16.1 release? This is affecting a big customer of mine/ours.

@samsmithnz - Unfortunately, not yet.  The internal changes around how to sign projects have created significant complications for getting these releases signed.  I'm still engaging with the appropriate teams internally to get unblocked, but the progress here continues to be much slower than desired.

**Comment by HowardWolosky** [comment]
[`0.16.1` has been successfully signed and published to PowerShellGallery.](https://www.powershellgallery.com/packages/PowerShellForGitHub/0.16.1)  This proves out the new approach I need to use to sign releases moving forward.  It's now a manual approach (can't use an Azure Pipeline anymore), but it at least gets things unblocked for the project.

**Pull request merged**
