### PR TITLE
Fix GitHubRepositorySecurityFix tests

### LINKED ISSUE #269: Enable-GitHubRepositorySecurityFix is Failing if Vulnerability Alerts are not Enabled
#### Issue Details

It looks like the GitHub repository [Enable Automated Security Fixes](https://docs.github.com/en/rest/reference/repos#enable-automated-security-fixes) API has changed so that now enabling automated security fixes has a dependency of [Automated Vulnerability Alerts](https://docs.github.com/en/rest/reference/repos#enable-vulnerability-alerts) being enabled on the repo. Previously this was not the case.

This is affecting the PowerShellForGitHub unit tests which are now failing in the `Describe 'GitHubRepositories\Enable-GitHubRepositorySecurityFix'` and `Describe 'GitHubRepositories\Disable-GitHubRepositorySecurityFix'` GitHubRepositories tests.

#### Steps to reproduce the issue
```powershell
$repo = New-GitHubRepository -RepositoryName ([Guid]::NewGuid().Guid)
Enable-GitHubRepositorySecurityFix -Uri  $repo.svn_url
```

#### Verbose logs showing the problem

```powershell
Invoke-WebRequest: Z:\Users\Simon\Documents\GitHub\X-Guardian\PowerShellForGitHub\GitHubCore.ps1:301:19
Line |
 301 |          $result = Invoke-WebRequest @params
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"message":"Vulnerability alerts must be enabled to configure automated security
     | fixes.","documentation_url":"https://docs.github.com/rest/reference/repos#enable-automated-security-fixes"}
```

#### Suggested solution to the issue

To fix the unit tests, add `Enable-GitHubRepositoryVulnerabilityAlert -Uri $repo.svn_url` to the `BeforeAll` block of the  `Describe 'GitHubRepositories\Enable-GitHubRepositorySecurityFix'` and `Describe 'GitHubRepositories\Disable-GitHubRepositorySecurityFix'` GitHubRepositories tests.

#### Requested Assignment

- If possible, I would like to fix this.

#### Operating System

```
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 1903
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}
```

#### PowerShell Version

```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

#### Module Version

```
Running: 0.14.0
Installed:
```

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Description

This PR fixes the `Describe 'GitHubRepositories\Enable-GitHubRepositorySecurityFix'` and `Describe 'GitHubRepositories\Disable-GitHubRepositorySecurityFix'` GitHubRepositories tests following on from the change to the GitHub Automated Security Fixes API.

#### Issues Fixed

- Fixes #269 

#### References

[Enable Automated Security Fixes](https://docs.github.com/en/rest/reference/repos#enable-automated-security-fixes)

#### Checklist

- [ ] ~~You actually ran the code that you just wrote, especially if you did just "one last quick change".~~
- [ ] ~~Comment-based help added/updated, including examples.~~
- [ ] ~~[Static analysis](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#static-analysis) is reporting back clean.~~
- [ ] ~~New/changed code adheres to our [coding guidelines](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#coding-guidelines).~~
- [ ] ~~[Formatters were created](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#formatters) for any new types being added.~~
- [ ] ~~New/changed code continues to [support the pipeline](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#pipeline-support).~~
- [ ] ~~Changes to the manifest file follow the [manifest guidance](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#module-manifest).~~
- [x] Unit tests were added/updated and are all passing. See [testing guidelines](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#testing).  This includes making sure that all pipeline input variations have been covered.
- [ ] ~~Relevant usage examples have been added/updated in [USAGE.md](https://github.com/microsoft/PowerShellForGitHub/blob/master/USAGE.md).~~
- [ ] ~~If desired, ensure your name is added to our [Contributors list](https://github.com/microsoft/PowerShellForGitHub/blob/master/CONTRIBUTING.md#contributors)~~

### CODE REVIEW

**Comment by X-Guardian** [comment]
@HowardWolosky, can you run the CI on this PR?

**Comment by X-Guardian** [comment]
I don't know what happened to the Linux and MacOS tests for this CI.

**Comment by HowardWolosky** [comment]
I've kicked off [a new CI for master](https://dev.azure.com/ms/PowerShellForGitHub/_build/results?buildId=99723&view=results) to see if master will fail now on Linux and macOS the same way that this CI has.
The [previous CI from master on Monday](https://dev.azure.com/ms/PowerShellForGitHub/_build/results?buildId=98890&view=results) succeeded just fine for all platforms.

**Comment by X-Guardian** [comment]
I can see that CI failed too, and I think I know what the problem is. GitHub are starting to change the default branch that is created with new repositories from 'master' to 'main', see: https://github.com/github/renaming. The first test that is consistently failing, `Describe 'GitHubBranches\Get-GitHubRepositoryBranchProtectionRule'` assumes that the default branch name for a newly created repo is 'master', which I'm wondering maybe now not the case for the GitHub accounts you are using for the MacOS and Linux unit tests.

**Comment by HowardWolosky** [comment]
> I can see that CI failed too, and I think I know what the problem is. GitHub are starting to change the default branch that is created with new repositories from 'master' to 'main', see: https://github.com/github/renaming. The first test that is consistently failing, `Describe 'GitHubBranches\Get-GitHubRepositoryBranchProtectionRule'` assumes that the default branch name for a newly created repo is 'master', which I'm wondering maybe now not the case for the GitHub accounts you are using for the MacOS and Linux unit tests.

That's a great call out, and I've opened #273 to track that, but I don't think that's what is going on here.  In I think it just happens to be coincidence where those it might just be pure coincidence.  I think those tests are around 60 in from the start.

I logged-in to the Linux CI account to check to see if there was a setting that we got opted into to test out the `master`->`main` change, but I don't think that's what's going on.   Apparently, the account has been flagged, and its rate limit has been dropped down _substantially_ to `60 requests per 12 hours` I think.  Same for the account use for macOS.

I'm reaching out to GitHub support to see what can be done for getting those accounts unflagged/unblocked.

**Comment by HowardWolosky** [comment]
Will proceed with getting some of these changes merged-in while I await a response from GitHub support on the account issues.

**Pull request merged**
